---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Puedes desplegar el operador Trident e instalar Trident usando Helm. Este proceso aplica a instalaciones donde las imĂ¡genes de contenedor requeridas por Trident se almacenan en un registro privado. 
---
= Implementa el operador de Trident usando Helm (modo sin conexiĂ³n)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes desplegar el operador Trident e instalar Trident usando Helm. Este proceso aplica a instalaciones donde las imĂ¡genes de contenedor requeridas por Trident se almacenan en un registro privado. Si no tienes un registro de imĂ¡genes privado, usa el link:kubernetes-deploy-helm.html["proceso para la implementaciĂ³n estĂ¡ndar"].



== InformaciĂ³n crĂ­tica sobre Trident 25.10

*Debes leer la siguiente informaciĂ³n crĂ­tica sobre Trident.*

.<strong>InformaciĂ³n crĂ­tica sobre Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 ya es compatible con Trident. Actualiza Trident antes de actualizar Kubernetes.
* Trident impone estrictamente el uso de la configuraciĂ³n de multivĂ­a en entornos SAN, con un valor recomendado de `find_multipaths: no` en el archivo multipath.conf.
+
El uso de una configuraciĂ³n sin multivĂ­a o el uso de `find_multipaths: yes` o `find_multipaths: smart` en el archivo multipath.conf provocarĂ¡ fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versiĂ³n 21.07.



=====
====


== Implementa el operador Trident e instala Trident usando Helm

Usando el Trident link:https://netapp.github.io/trident-helm-chart["Helm Chart"^] puedes desplegar el operador Trident e instalar Trident en un solo paso.

Revisa link:../trident-get-started/kubernetes-deploy.html["la visiĂ³n general de la instalaciĂ³n"] para asegurarte de que cumpliste los requisitos previos de instalaciĂ³n y seleccionaste la opciĂ³n de instalaciĂ³n correcta para tu entorno.

.Antes de empezar
AdemĂ¡s de link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["requisitos previos de despliegue"] tĂº necesitas link:https://v3.helm.sh/["Helm versiĂ³n 3"^].


IMPORTANT: Cuando instales Trident en un repositorio privado, si estĂ¡s usando el modificador `imageRegistry` para especificar la ubicaciĂ³n del repositorio, no uses `/netapp/` en la ruta del repositorio.

.Pasos
. Agrega el repositorio Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Usa `helm install` y especifica un nombre para tu deployment y la ubicaciĂ³n del image registry. Tu link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["ImĂ¡genes de Trident y CSI"] puede estar ubicado en un registry o en diferentes registries, pero todas las imĂ¡genes CSI deben estar en el mismo registry. En los ejemplos, `100.2506.0` es la versiĂ³n de Trident que estĂ¡s instalando.
+
[role="tabbed-block"]
====
.ImĂ¡genes en un registro
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.ImĂ¡genes en diferentes registros
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.10.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.10 --set tridentImage=<your-registry>/trident:25.10.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Si ya creaste un espacio de nombres para Trident, el parĂ¡metro `--create-namespace` no crearĂ¡ un espacio de nombres adicional.



Puedes usar `helm list` para revisar detalles de la instalaciĂ³n como nombre, espacio de nombres, chart, estado, versiĂ³n de la app y nĂºmero de revisiĂ³n.



== Pasa los datos de configuraciĂ³n durante la instalaciĂ³n

Hay dos formas de pasar datos de configuraciĂ³n durante la instalaciĂ³n:

[cols="2"]
|===
| OpciĂ³n | DescripciĂ³n 


| `--values` (o `-f`)  a| 
Especifica un archivo YAML con anulaciones. Esto se puede especificar varias veces y el archivo mĂ¡s a la derecha tendrĂ¡ prioridad.



| `--set`  a| 
Especifica las modificaciones en la lĂ­nea de comandos.

|===
Por ejemplo, para cambiar el valor por defecto de `debug`, ejecuta el siguiente comando donde `100.2506.0` es la versiĂ³n de Trident que estĂ¡s instalando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----
Para aĂ±adir el valor nodePrep, ejecuta el siguiente comando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== Opciones de configuraciĂ³n

Esta tabla y el archivo `values.yaml`, que es parte del Helm chart, proporcionan la lista de claves y sus valores predeterminados.


WARNING: No elimines la afinidad predeterminada del archivo values.yaml. Cuando quieras proporcionar una afinidad personalizada, amplĂ­a la afinidad predeterminada.

[cols="3"]
|===
| OpciĂ³n | DescripciĂ³n | Predeterminado 


| `nodeSelector` | Etiquetas de nodo para la asignaciĂ³n de pod |  


| `podAnnotations` | Anotaciones del pod |  


| `deploymentAnnotations` | Anotaciones de deployment |  


| `tolerations` | Tolerancias para la asignaciĂ³n de pods |  


| `affinity` | Afinidad para la asignaciĂ³n de pods  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimines la afinidad predeterminada del archivo values.yaml. Cuando quieras proporcionar una afinidad personalizada, amplĂ­a la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para pods. Consulta link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entender los pods de controlador y los pods de nodo"] para mĂ¡s detalles. |  


| `tridentControllerPluginTolerations` | Anula las tolerancias de Kubernetes para los pods. Consulta link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entender los pods de controlador y los pods de nodo"] para mĂ¡s detalles. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para pods. Consulta link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entender los pods de controlador y los pods de nodo"] para mĂ¡s detalles. |  


| `tridentNodePluginTolerations` | Anula las tolerancias de Kubernetes para los pods. Consulta link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entender los pods de controlador y los pods de nodo"] para mĂ¡s detalles. |  


| `imageRegistry` | Identifica el registro para el `trident-operator`, `trident` y otras imĂ¡genes. DĂ©jalo vacĂ­o para aceptar el valor predeterminado. IMPORTANTE: cuando instales Trident en un repositorio privado, si usas el switch `imageRegistry` para especificar la ubicaciĂ³n del repositorio, no uses `/netapp/` en la ruta del repositorio. | "" 


| `imagePullPolicy` | Establece la polĂ­tica de extracciĂ³n de imĂ¡genes para el `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Establece los secretos de extracciĂ³n de imĂ¡genes para las `trident-operator`, `trident` y otras imĂ¡genes. |  


| `kubeletDir` | Permite anular la ubicaciĂ³n del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite establecer el nivel de registro del operador Trident en: `trace`, `debug`, `info`, `warn`, `error` o `fatal`. | `"info"` 


| `operatorDebug` | Permite establecer el nivel de registro del operador Trident en modo debug. | `true` 


| `operatorImage` | Permite la anulaciĂ³n completa de la imagen para `trident-operator`. | "" 


| `operatorImageTag` | Permite anular la etiqueta de la  `trident-operator` imagen. | "" 


| `tridentIPv6` | Permite habilitar Trident para trabajar en clĂºsteres IPv6. | `false` 


| `tridentK8sTimeout`  a| 
Anula el tiempo de espera predeterminado de 180 segundos para la mayorĂ­a de las operaciones de la API de Kubernetes (si no es cero, en segundos).


NOTE: El `tridentK8sTimeout` parĂ¡metro solo es aplicable para la instalaciĂ³n de Trident.
| `180` 


| `tridentHttpRequestTimeout` | Anula el tiempo de espera predeterminado de 90 segundos para las solicitudes HTTP, con `0s` siendo una duraciĂ³n infinita para el tiempo de espera. No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite deshabilitar los informes periĂ³dicos de AutoSupport de Trident. | `false` 


| `tridentAutosupportImageTag` | Permite sobrescribir la etiqueta de la imagen para el contenedor Trident AutoSupport. | `<version>` 


| `tridentAutosupportProxy` | Permite que el contenedor Trident AutoSupport se comunique con la central a travĂ©s de un proxy HTTP. | "" 


| `tridentLogFormat` | Establece el formato de registro de Trident (`text` o `json`). | `"text"` 


| `tridentDisableAuditLog` | Desactiva el auditor de registros de Trident. | `true` 


| `tridentLogLevel` | Permite establecer el nivel de registro de Trident en: `trace`, `debug`, `info`, `warn`, `error` o `fatal`. | `"info"` 


| `tridentDebug` | Permite establecer el nivel de registro de Trident en `debug`. | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo especĂ­ficos de Trident para el registro de trazas o la supresiĂ³n de logs. | "" 


| `tridentLogLayers` | Permite habilitar capas especĂ­ficas de Trident para el registro de trazas o la supresiĂ³n de logs. | "" 


| `tridentImage` | Permite la anulaciĂ³n completa de la imagen para Trident. | "" 


| `tridentImageTag` | Permite anular la etiqueta de la imagen para Trident. | "" 


| `tridentProbePort` | Permite anular el puerto predeterminado usado para las sondas de liveness/readiness de Kubernetes. | "" 


| `windows` | Permite que Trident se instale en el nodo trabajador de Windows. | `false` 


| `enableForceDetach` | Permite activar la funciĂ³n de desvinculaciĂ³n forzada. Puedes automatizar el proceso de desvinculaciĂ³n forzada mediante la integraciĂ³n con el operador de comprobaciĂ³n del estado del nodo (NHC). Para mĂ¡s informaciĂ³n, consulta link:../trident-reco/force-detach.html["Automatizando la conmutaciĂ³n por error de aplicaciones con estado con Trident"]. | `false` 


| `excludePodSecurityPolicy` | Excluye la polĂ­tica de seguridad del pod de operador de la creaciĂ³n. | `false` 


| `nodePrep`  a| 
Permite que Trident prepare los nodos del clĂºster de Kubernetes para gestionar volĂºmenes usando el protocolo de almacenamiento de datos especificado. *Actualmente,  `iscsi` es el Ăºnico valor admitido.*


NOTE: A partir de OpenShift 4.19, la versiĂ³n mĂ­nima de Trident compatible con esta funciĂ³n es 25.06.1.
|  


| `resources`  a| 
Establece los lĂ­mites y las solicitudes de recursos de Kubernetes para los pods del controlador, nodo y operador de Trident. Puedes configurar la CPU y la memoria de cada contenedor y sidecar para gestionar la asignaciĂ³n de recursos en Kubernetes.

Para obtener mĂ¡s informaciĂ³n sobre cĂ³mo configurar las solicitudes y los lĂ­mites de recursos, consulta link:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["GestiĂ³n de recursos para pods y contenedores"^].

[WARNING]
====
* NO cambies los nombres de ningĂºn contenedor ni de ningĂºn campo.
* NO cambies la sangrĂ­a: la sangrĂ­a de YAML es fundamental para que se analice correctamente.


====
[NOTE]
====
* No se aplican lĂ­mites por defecto: solo las solicitudes tienen valores por defecto.
* Los nombres de los contenedores figuran tal como aparecen en las especificaciones del pod.
* Los sidecars aparecen debajo de cada contenedor principal.
* Revisa el campo `status.CurrentInstallationParams` del TORC para ver los valores que estĂ¡n aplicados ahora.


==== a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----
|===