---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Puedes actualizar Trident Protect a la última versión para aprovechar las nuevas funciones o correcciones de errores. 
---
= Actualizar Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puedes actualizar Trident Protect a la última versión para aprovechar las nuevas funciones o correcciones de errores.

[NOTE]
====
* Al actualizar desde la versión 24.10, las instantáneas que se estén ejecutando durante la actualización pueden fallar. Este fallo no impide que se creen futuras instantáneas, ya sean manuales o programadas. Si una instantánea falla durante la actualización, puedes crear manualmente una nueva instantánea para asegurarte de que tu aplicación esté protegida.
+
Para evitar posibles fallos, puedes desactivar todas las programaciones de instantáneas antes de la actualización y volver a activarlas después. Sin embargo, esto provoca que se pierdan las instantáneas programadas durante el periodo de actualización.

* Para instalaciones de registro privado, asegúrate de que el Helm chart requerido y las imágenes para la versión de destino estén disponibles en tu registro privado, y verifica que tus valores personalizados de Helm sean compatibles con la nueva versión del chart. Para más información, consulta link:trident-protect-installation.html["Instala Trident Protect desde un registro privado"].


====
Para actualizar Trident Protect, realiza los siguientes pasos.

.Pasos
. Actualiza el repositorio de Trident Helm:
+
[source, console]
----
helm repo update
----
. Actualiza los CRD de Trident Protect:
+

NOTE: Este paso es necesario si estás actualizando desde una versión anterior a la 25.06, ya que los CRDs ahora están incluidos en el Helm chart de Trident Protect.

+
.. Ejecuta este comando para cambiar la gestión de los CRD de `trident-protect-crds` a `trident-protect`:
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Ejecuta este comando para borrar el secreto de Helm del chart `trident-protect-crds`:
+

NOTE: No desinstales el chart `trident-protect-crds` usando Helm, ya que esto podría eliminar tus CRDs y cualquier dato relacionado.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Actualiza Trident Protect:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE: Puedes configurar el nivel de registro durante la actualización añadiendo `--set logLevel=debug` al comando de actualización. El nivel de registro predeterminado es `warn`. Se recomienda el registro de depuración para la solución de problemas, ya que ayuda al soporte de NetApp a diagnosticar problemas sin necesidad de cambiar el nivel de registro ni reproducir el problema.


